---
title: "5243_project2"
author: "Group 5"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---


```{r} 
if (!require("DT")) install.packages('DT')
if (!require("dtplyr")) install.packages('dtplyr')
if (!require("lubridate")) install.packages('lubridate')
if (!require("ggmap")) install.packages('ggmap')
if (!require("choroplethrZip")) {
  #install.packages("devtools")
  library(devtools)
  install_github('arilamstein/choroplethrZip@v1.5.0')}
if (!require("choroplethr")) install.packages("choroplethr")
if (!require("devtools")) install.packages("devtools")
if (!require("choroplethrZip")) 
  devtools::install_github('arilamstein/choroplethrZip@v1.5.0')
if (!require("ggplot2")) devtools::install_github("hadley/ggplot2")
if (!require("ggmap")) devtools::install_github("dkahle/ggmap")
if (!require("shiny")) install.packages("shiny")
```


```{r} 
library(leaflet)
library(ggplot2)
library(reshape2)
library(dtplyr)
library(dplyr)
library(DT)
library(lubridate)
library(devtools)
library(shiny)
library(choroplethrZip)
library(caret)
library(tmap)
library(tmaptools)
```


```{r} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

# Covid Count Dataset
covid_cases = read.csv('covid_cases.csv')

# set the first column of timestamps as row name
rownames(covid_cases) = covid_cases$date_of_interest
covid_cases$date_of_interest = NULL

# TEST
datatable(sample_n(covid_cases, 5))
ncol(covid_cases)

# seperating the dataset into multiple dataframes
data_general = covid_cases[, 1:10]
bronx_covid = select(covid_cases, contains("BX"))
brooklyn_covid = select(covid_cases, contains("BK"))
manhattan_covid = select(covid_cases, contains("MN"))
queens_covid = select(covid_cases, contains("QN"))
staten_island_covid = select(covid_cases, contains("SI"))

case_count = subset(covid_cases, select = c("CASE_COUNT", "BX_CASE_COUNT",
                                            "BK_CASE_COUNT", "MN_CASE_COUNT", "QN_CASE_COUNT",
                                            "SI_CASE_COUNT"))
death_count = subset(covid_cases, select = c("DEATH_COUNT", "BX_DEATH_COUNT",
                                             "BK_DEATH_COUNT", "MN_DEATH_COUNT", "QN_DEATH_COUNT",
                                             "SI_DEATH_COUNT"))
hospitalized_count = subset(covid_cases, select = c("HOSPITALIZED_COUNT", "BX_HOSPITALIZED_COUNT",
                                                    "BK_HOSPITALIZED_COUNT", "MN_HOSPITALIZED_COUNT", "QN_HOSPITALIZED_COUNT",
                                                    "SI_HOSPITALIZED_COUNT"))

case_count = rbind(colSums(case_count), case_count)
datatable(sample_n(case_count, 5))

death_count = rbind(colSums(death_count), death_count)
datatable(sample_n(death_count, 5))

hospitalized_count = rbind(colSums(hospitalized_count), hospitalized_count)
datatable(sample_n(hospitalized_count, 5))
```


```{r} 
# assigning the zip of the boroughs to variables
all_bx_zip = c(10451:10475)
all_bk_zip = c(11201:11256)
all_mn_zip = c(10001:10282)
all_qn_zip = c(11004:11109, 11351:11697)
all_si_zip = c(10301:10314)
all_nyc_zip = c(all_bx_zip, all_bk_zip, all_mn_zip, all_qn_zip, all_si_zip)
```


```{r} 
# License_Application and Legally_Operating_business Data Cleaning
License_Applications = read.csv("License_Applications.csv")
Legally_Operating_Businesses <- read.csv("Legally_Operating_Businesses.csv")

Legal <- Legally_Operating_Businesses[,c('DCA.License.Number','Borough.Code')] 

License_merged <- merge(License_Applications, Legal, by.x='License.Number', by.y='DCA.License.Number')

License_merged_Ny <- filter(License_merged, `Zip` %in% all_nyc_zip)

#clean data
License_merged_Ny$Start.Date <- mdy(License_merged_Ny$Start.Date)
License_merged_Ny$End.Date <- mdy(License_merged_Ny$End.Date)
month <- month(License_merged_Ny$Start.Date)
year <- year(License_merged_Ny$Start.Date)
License_merged_Ny <- mutate(License_merged_Ny, Start_Month= paste(month, year, sep='-'))
License_merged_Ny <- mutate(License_merged_Ny, Start_Year= year)
License_merged_Ny <- mutate(License_merged_Ny, Processing_time = as.numeric(difftime(License_merged_Ny$End.Date,License_merged_Ny$Start.Date,units = 'days')))
License_merged_Ny_sub <- License_merged_Ny[,c('License.Number','License.Type','License.Category','Start.Date',
                                              'End.Date','Start_Month','Start_Year','Processing_time','Longitude','Latitude','Status', 'Borough.Code', 'Zip', 'City')]
License_merged_clean <- na.omit(License_merged_Ny_sub)

#write.csv(License_merged_clean, file = "data_clean.csv", row.names = FALSE)

#business and individual
business_data <-  filter(License_merged_clean, `License.Type` == 'Business')
individual_data <- filter(License_merged_clean, `License.Type` == 'Individual')

#business
Service <- c('Third Party Food Delivery',"Construction Labor Provider","Storage Warehouse",
             "Home Improvement Contractor","Debt Collection Agency","Laundries","Car Wash",
             "Laundry","Employment Agency","Electronic & Appliance Service","Scale Dealer Repairer",
             "Commercial Lessor","Process Serving Agency","Scrap Metal Processor")

Entertainment <-c("Cabaret","Bingo Game Operator","Pool or Billiard Room","Amusement Device Temporary",
                  "Gaming Cafe","Games of Chance","Amusement Device Permanent", 
                  "Amusement Device Portable","Amusement Arcade","Sidewalk Cafe")

Retail <- c("Secondhand Dealer - Firearms","Ticket Seller Business","Dealer In Products", 
            "Stoop Line Stand","Electronics Store","Newsstand","Special Sale","Laundry Jobber", 
            "Secondhand Dealer - General","Secondhand Dealer - Auto","Electronic Cigarette Dealer", 
            "Tobacco Retail Dealer","General Vendor Distributor","Pawnbroker","Catering Establishment", 
            "Auction House Premises")

Trans <- c("Sightseeing Bus","Booting Company","Horse Drawn Cab Owner","Parking Lot", 
           "Tow Truck Company","Garage and Parking Lot","Pedicab Business","Tow Truck Exemption","Garage")

Businessdata_Service <- filter(business_data, `License.Category` %in% Service)
Businessdata_Entertainment <- filter(business_data, `License.Category` %in% Entertainment)
Businessdata_Retail <- filter(business_data, `License.Category` %in% Retail)
Businessdata_Trans <- filter(business_data, `License.Category` %in% Trans)

#individual
Service_1 <- c('Tow Truck Driver','Pedicab Driver','Horse Drawn Driver','Home Improvement Salesperson', 
               'Temporary Street Fair Vendor','General Vendor','Ticket Seller','Sightseeing Guide','Auctioneer')

Skilled_Wokers<-c('Process Server Individual','Motion Picture Projectionist','Locksmith Apprentice','Locksmith')

Individualdata_Service <- filter(individual_data, `License.Category` %in% Service_1)
Individualdata_Skilled_Wokers <- filter(individual_data, `License.Category` %in% Skilled_Wokers)

```



```{r} 
# Seperate the License_merged_clean before and after 2.29.2020
# 804 days since covid

# Cutoff Date 
cutoff_date = as.Date("2020-02-29")
# Before the cutoff date
License_before = License_merged_clean[as.Date("2017-11-6") <= License_merged_clean$Start.Date
                                      & License_merged_clean$Start.Date < cutoff_date,]
# After the cutoff date
License_after = License_merged_clean[License_merged_clean$Start.Date >= cutoff_date,]


cat("number of rows in License_merged_clean:", nrow(License_merged_clean), "\n")
cat("number of rows in License_before:", nrow(License_before), "\n")
cat("number of rows in License_after:", nrow(License_after), "\n")
```


```{r} 

# Before COVID
license_bronx_before = filter(License_before, `Zip` %in% all_bx_zip)
license_brooklyn_before = filter(License_before, `Zip` %in% all_bk_zip)
license_manhattan_before = filter(License_before, `Zip` %in% all_mn_zip)
license_queens_before = filter(License_before, `Zip` %in% all_qn_zip)
license_staten_island_before = filter(License_before, `Zip` %in% all_si_zip)
```


```{r} 

# After COVID
license_bronx_after = filter(License_after, `Zip` %in% all_bx_zip)
license_brooklyn_after = filter(License_after, `Zip` %in% all_bk_zip)
license_manhattan_after = filter(License_after, `Zip` %in% all_mn_zip)
license_queens_after = filter(License_after, `Zip` %in% all_qn_zip)
license_staten_island_after = filter(License_after, `Zip` %in% all_si_zip)
```


```{r} 
# Bronx Map Before COVID
# Convert the table to a data frame
bronx_count_before = data.frame(count = table(license_bronx_before$Zip))
colnames(bronx_count_before) = c('zip', 'counts')

# Convert zip code to character string
bronx_count_before$zip = as.character(bronx_count_before$zip)

# Rename columns to "region" and "value"
user.df = data.frame(region = bronx_count_before$zip, value = bronx_count_before$counts)

# Create the choropleth map
zip_choropleth(user.df, 
               title = "Number of Business Applications before COVID in Bronx", 
               legend = "counts",
               county_zoom = 36005)
```


```{r} 

# Bronx Map after COVID
# Convert the table to a data frame
bronx_count_after = data.frame(count = table(license_bronx_after$Zip))
colnames(bronx_count_after) = c('zip', 'counts')

# Convert zip code to character string
bronx_count_after$zip = as.character(bronx_count_after$zip)

# Rename columns to "region" and "value"
user.df = data.frame(region = bronx_count_after$zip, value = bronx_count_after$counts)

# Create the choropleth map
zip_choropleth(user.df, 
               title = "Number of Business Applications after COVID in Bronx", 
               legend = "counts",
               county_zoom = 36005)
```


```{r} 

# Brooklyn Map Before COVID
# Convert the table to a data frame
brooklyn_count_before = data.frame(count = table(license_brooklyn_before$Zip))
colnames(brooklyn_count_before) = c('zip', 'counts')

# Convert zip code to character string
brooklyn_count_before$zip <- as.character(brooklyn_count_before$zip)

# Rename columns to "region" and "value"
user.df = data.frame(region = brooklyn_count_before$zip, value = brooklyn_count_before$counts)


# Create the choropleth map
zip_choropleth(user.df, 
               title = "Number of Business Applications before COVID in Brooklyn", 
               legend = "counts",
               county_zoom = 36047)
```


```{r} 

# Brooklyn Map after COVID
# Convert the table to a data frame
brooklyn_count_after = data.frame(count = table(license_brooklyn_after$Zip))
colnames(brooklyn_count_after) = c('zip', 'counts')

# Convert zip code to character string
brooklyn_count_after$zip = as.character(brooklyn_count_after$zip)

# Rename columns to "region" and "value"
user.df = data.frame(region = brooklyn_count_after$zip, value = brooklyn_count_after$counts)


# Create the choropleth map
zip_choropleth(user.df, 
               title = "Number of Business Applications after COVID in Brooklyn", 
               legend = "counts",
               county_zoom = 36047)
```


```{r} 

# Queens Map before COVID
# Convert the table to a data frame
queens_count_before = data.frame(count = table(license_queens_before$Zip))
colnames(queens_count_before) = c('zip', 'counts')

# Convert zip code to character string
queens_count_before$zip = as.character(queens_count_before$zip)

# Rename columns to "region" and "value"
user.df = data.frame(region = queens_count_before$zip, value = queens_count_before$counts)

# Create the choropleth map
zip_choropleth(user.df, 
               title = "Number of Business Applications before COVID in Queens", 
               legend = "counts",
               county_zoom = 36081)
```


```{r} 

# Queens Map after COVID
# Convert the table to a data frame
queens_count_after = data.frame(count = table(license_queens_after$Zip))
colnames(queens_count_after) = c('zip', 'counts')

# Convert zip code to character string
queens_count_after$zip = as.character(queens_count_after$zip)

# Rename columns to "region" and "value"
user.df = data.frame(region = queens_count_after$zip, value = queens_count_after$counts)

# Create the choropleth map
zip_choropleth(user.df, 
               title = "Number of Business Applications after COVID in Queens", 
               legend = "counts",
               county_zoom = 36081)
```


```{r} 

# Manhattan Map before COVID
# Convert the table to a data frame
manhattan_count_before = data.frame(count = table(license_manhattan_before$Zip))
colnames(manhattan_count_before) = c('zip', 'counts')

# Convert zip code to character string
manhattan_count_before$zip = as.character(manhattan_count_before$zip)

# Rename columns to "region" and "value"
user.df = data.frame(region = manhattan_count_before$zip, value = manhattan_count_before$counts)

# Create the choropleth map
zip_choropleth(user.df, 
               title = "Number of Business Applications before COVID in Manhattan", 
               legend = "counts",
               county_zoom = 36061)
```


```{r} 

# Manhattan Map after COVID
# Convert the table to a data frame
manhattan_count_after = data.frame(count = table(license_manhattan_after$Zip))
colnames(manhattan_count_after) = c('zip', 'counts')

# Convert zip code to character string
manhattan_count_after$zip = as.character(manhattan_count_after$zip)

# Rename columns to "region" and "value"
user.df = data.frame(region = manhattan_count_after$zip, value = manhattan_count_after$counts)

# Create the choropleth map
zip_choropleth(user.df, 
               title = "Number of Business Applications after COVID in Manhattan", 
               legend = "counts",
               county_zoom = 36061)
```


```{r} 

# Staten Island Map before COVID
# Convert the table to a data frame
statenisland_count_before = data.frame(count = table(license_staten_island_before$Zip))
colnames(statenisland_count_before) = c('zip', 'counts')

# Convert zip code to character string
statenisland_count_before$zip = as.character(statenisland_count_before$zip)

# Rename columns to "region" and "value"
user.df = data.frame(region = statenisland_count_before$zip, value = statenisland_count_before$counts)

# Create the choropleth map
zip_choropleth(user.df, 
               title = "Number of Business Applications before COVID in Staten Island", 
               legend = "counts",
               county_zoom = 36085)
```


```{r} 

# Staten Island Map after COVID
# Convert the table to a data frame
statenisland_count_after = data.frame(count = table(license_staten_island_after$Zip))
colnames(statenisland_count_after) = c('zip', 'counts')

# Convert zip code to character string
statenisland_count_after$zip = as.character(statenisland_count_after$zip)

# Rename columns to "region" and "value"
user.df = data.frame(region = statenisland_count_after$zip, value = statenisland_count_after$counts)

# Create the choropleth map
zip_choropleth(user.df, 
               title = "Number of Business Applications after COVID in Staten Island", 
               legend = 5,
               county_zoom = 36085)
```













